import pandas as pd
import matplotlib.pyplot as plt

df = pd.read_csv('hw3_avocado.csv')
df.info()
print(df.nunique())
pd.set_option('display.max_rows', None)
print(df)
print("First 5 rows, first 4 columns:\n", df.iloc[:5, :4])
print("First 5 rows, last 4 columns:\n", df.iloc[:5, -4:])
print("Last 5 rows, first 4 columns:\n", df.iloc[-5:, :4])
print("Last 5 rows, last 4 columns:\n", df.iloc[-5:, -4:])
print(df[['Total Volume', 'AveragePrice', 'region']].head())
print(df.AveragePrice.head())
df['EstimatedRevenue'] = df['Total Volume'] * df['AveragePrice']
print(df[['Total Volume', 'AveragePrice', 'EstimatedRevenue']].head())
grouped_df = df.groupby(['region', 'type']).agg({'AveragePrice': 'mean'}).reset_index()
print(grouped_df.head())
stats_df = df.groupby('year')['Total Volume'].agg(['mean', 'median', 'std'])
stats_df.plot(kind='bar', y=['mean', 'median', 'std'], title='Total Volume by Year')
plt.ylabel('Total Volume')
plt.show()
bags_df = df.groupby('type')[['Small Bags', 'Large Bags', 'XLarge Bags']].sum().reset_index()
print(bags_df)
bags_df.plot(kind='bar', x='type', stacked=True, title='Number of Bags by Type')
plt.ylabel('Total Bags')
plt.show()
df.plot(kind='scatter', x='Total Volume', y='AveragePrice', title='Total Volume vs Average Price')
plt.show()
